#!/usr/bin/env python3
"""Fill MODEL_CARD.md's metrics from an eval run.

Only the block between the AUTOGENERATED markers is rewritten. The prose
sections — intended use, limitations, the not-a-diagnostic-device statement —
are hand-written and must stay that way: a model card whose caveats are
generated is a caveat nobody wrote and nobody owns.

Usage::

    python scripts/render_model_card.py eval_results.json
    python scripts/render_model_card.py eval_results.json --check   # CI drift check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.eval_thresholds import KNOWN_ISSUES, gates_for  # noqa: E402

BEGIN = "<!-- BEGIN AUTOGENERATED METRICS -->"
END = "<!-- END AUTOGENERATED METRICS -->"

VARIANT_LABELS = {
    "phase0": "Phase 0 — static Residual U-Net + deep supervision",
    "phase4a": "Phase 4a — Phase 0, hybrid-crossover pruned",
    "phase2": "Phase 2 — temporal, 2D U-Net + temporal self-attention",
    "phase4b": "Phase 4b — Phase 2, backbone pruned, TAM intact",
}


def _fmt(value, suffix: str = "") -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:g}{suffix}"
    return f"{value}{suffix}"


def render_block(report: dict) -> str:
    variants = report.get("variants") or {}
    lines = [
        BEGIN,
        "",
        f"*Generated by `scripts/evaluate.py` on {report.get('generated_at', 'unknown date')}.*",
        "",
        f"**Evaluation set:** the {_evaluated_count(variants)} demo subjects in "
        "`demo_subjects/`, scored against the reference head circumference in "
        "`training_set_pixel_size_and_HC.csv` (HC18 annotations).",
        "",
        "| Variant | HC MAE (mm) | Max error (mm) | Measurable | Within ISUOG ±3 mm | Mean latency (ms) |",
        "|---|---|---|---|---|---|",
    ]

    for key, label in VARIANT_LABELS.items():
        entry = variants.get(key)
        if entry is None:
            lines.append(f"| {label} | not evaluated | — | — | — | — |")
            continue
        if not entry.get("loaded"):
            lines.append(f"| {label} | **checkpoint not loaded** | — | — | — | — |")
            continue
        m = entry.get("metrics") or {}
        rate = m.get("measurable_rate")
        isuog = m.get("isuog_pass_rate")
        lines.append(
            f"| {label} | {_fmt(m.get('hc_mae_mm'))} | {_fmt(m.get('hc_max_error_mm'))} | "
            f"{_fmt(round(rate * 100, 1) if rate is not None else None, '%')} | "
            f"{_fmt(round(isuog * 100, 1) if isuog is not None else None, '%')} | "
            f"{_fmt(m.get('mean_latency_ms'))} |"
        )

    reason = _dice_reason(variants)
    lines += [
        "",
        "### Release gates enforced in CI",
        "",
        "| Metric | Requirement |",
        "|---|---|",
    ]
    lines[-1] = "|---|---|---|"
    lines[-2] = "| Variant | Metric | Requirement |"
    for key in VARIANT_LABELS:
        for metric, (op, bound) in sorted(gates_for(key).items()):
            lines.append(f"| `{key}` | `{metric}` | {op} {bound} |")

    issues = {k: v for k, v in KNOWN_ISSUES.items() if k in variants}
    if issues:
        lines += ["", "### Known issues the gates currently accommodate", ""]
        for key, text in sorted(issues.items()):
            lines.append(f"- **`{key}`** — {text}")

    lines += [
        "",
        "A push to `main` that violates any of these does not deploy.",
        "",
        "### Why there is no Dice figure here",
        "",
        reason,
        "",
        "> These numbers come from 12 demo images through the deployed inference "
        "path. They are a **regression signal**, not a restatement of the paper "
        "metrics — the headline Dice and MAE in the README are from the full "
        "HC18 test set, which is not redistributed with this repository.",
        "",
        END,
    ]
    return "\n".join(lines)


def _evaluated_count(variants: dict) -> int:
    for entry in variants.values():
        metrics = entry.get("metrics") or {}
        if metrics.get("n_images"):
            return int(metrics["n_images"])
    return 0


def _dice_reason(variants: dict) -> str:
    for entry in variants.values():
        metrics = entry.get("metrics") or {}
        if metrics.get("dice_unavailable_reason"):
            return str(metrics["dice_unavailable_reason"])
    from scripts.eval_thresholds import DICE_UNAVAILABLE_REASON

    return DICE_UNAVAILABLE_REASON


def splice(card: str, block: str) -> str:
    if BEGIN not in card or END not in card:
        raise ValueError(
            f"MODEL_CARD.md is missing the {BEGIN} / {END} markers — refusing to "
            "overwrite hand-written prose."
        )
    head = card.split(BEGIN)[0]
    tail = card.split(END, 1)[1]
    return f"{head}{block}{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results")
    parser.add_argument("--card", default=str(REPO_ROOT / "MODEL_CARD.md"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the card is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    report = json.loads(Path(args.results).read_text())
    card_path = Path(args.card)
    card = card_path.read_text()
    updated = splice(card, render_block(report))

    if args.check:
        if updated != card:
            print("::error::MODEL_CARD.md is out of date. Run scripts/render_model_card.py.")
            return 1
        print("MODEL_CARD.md is up to date.")
        return 0

    if updated == card:
        print("MODEL_CARD.md already current — no change.")
        return 0
    card_path.write_text(updated)
    print(f"Updated {card_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
